### ISSUE TITLE
指令不全

### ISSUE THREAD

**Issue by gjmhmm8** [KiminoKaslana/YSGM_GUI#1]
https://www.iopq.net/thread-17117287-1-1.html
隐藏指令很多

**Comment by KiminoKaslana** [comment]
谢谢指路。之前一直不知道指令列表去哪里查看。如果需要使用未收录的指令，你可以直接输入或使用“收藏夹”功能。

**Comment by Liujunhua007** [comment]
> 谢谢指路。之前一直不知道指令列表去哪里查看。如果需要使用未收录的指令，你可以直接输入或使用“收藏夹”功能。

大佬，等有空了把这些加进去吗
